Repository rapidsai/ucxx, pull requests merged in 2023-11, with the labels that each got.

#125 Add argument to enable/disable endpoint error handling in benchmarks
  python/distributed-ucxx/distributed_ucxx/tests/test_ucxx.py
  python/ucxx/benchmarks/backends/ucxx_async.py
  python/ucxx/benchmarks/backends/ucxx_core.py
  python/ucxx/benchmarks/send_recv.py
Labels: feature request, non-breaking

#127 Update rapids cmake calls to use non-deprecated signatures
  cpp/cmake/thirdparty/get_gtest.cmake
  cpp/python/CMakeLists.txt
Labels: bug, non-breaking

#130 Build concurrency for nightly and merge triggers
  .github/workflows/build.yaml
Labels: improvement, non-breaking

#136 Set timeout for closing endpoints in Python
  python/ucxx/_lib/libucxx.pyx
  python/ucxx/_lib/ucxx_api.pxd
  python/ucxx/_lib_async/endpoint.py
Labels: bug, non-breaking
