Repository rapidsai/ucxx, pull requests merged in 2024-11, with the labels that each got.

#315 Fixes for AM and enable AM tests that were previously skipped
  ci/test_common.sh
  cpp/include/ucxx/request.h
  cpp/include/ucxx/request_am.h
  cpp/src/endpoint.cpp
  cpp/src/request_am.cpp
  python/ucxx/ucxx/_lib/libucxx.pyx
  python/ucxx/ucxx/_lib/ucxx_api.pxd
  python/ucxx/ucxx/_lib_async/tests/test_endpoint.py
  python/ucxx/ucxx/_lib_async/tests/test_from_worker_address_error.py
  python/ucxx/ucxx/_lib_async/tests/test_send_recv_two_workers.py
  python/ucxx/ucxx/_lib_async/tests/test_shutdown.py
Labels: bug, non-breaking

#319 enforce wheel size limits, README formatting in CI
  ci/build_wheel_distributed_ucxx.sh
  ci/build_wheel_libucxx.sh
  ci/build_wheel_ucxx.sh
  ci/validate_wheel.sh
  python/distributed-ucxx/pyproject.toml
  python/libucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#317 Replace uses of `__del__` with `weakref.finalize`
  ci/test_common.sh
  python/distributed-ucxx/distributed_ucxx/ucxx.py
  python/ucxx/ucxx/_lib_async/continuous_ucx_progress.py
  python/ucxx/ucxx/_lib_async/endpoint.py
  python/ucxx/ucxx/_lib_async/listener.py
Labels: bug, non-breaking

#324 Fix `test_from_worker_address_error[unreachable]` test
  python/ucxx/ucxx/_lib_async/tests/test_from_worker_address_error.py
Labels: bug, non-breaking

#322 prefer wheel-provided libucxx.so in load_library, use RTLD_LOCAL
  python/libucxx/libucxx/load.py
Labels: breaking, improvement

#323 Set PyNVML upper pin
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/recipes/ucxx/meta.yaml
  dependencies.yaml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#314 Add breaking change workflow trigger
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#335 Require approval to run CI on draft PRs
  .github/copy-pr-bot.yaml
Labels: improvement, non-breaking

#336 Adapt to rmm logger changes
  cpp/CMakeLists.txt
Labels: improvement, non-breaking
