Repository rapidsai/ucxx, pull requests merged in 2024-01, with the labels that each got.

#153 Fix segmentation fault on canceled requests that are not awaited
  cpp/include/ucxx/inflight_requests.h
  cpp/include/ucxx/worker.h
  cpp/src/endpoint.cpp
  cpp/src/inflight_requests.cpp
  cpp/src/worker.cpp
  python/distributed-ucxx/distributed_ucxx/tests/test_ucxx.py
  python/ucxx/_lib/libucxx.pyx
  python/ucxx/_lib/ucxx_api.pxd
Labels: bug, non-breaking

#157 Remove invalid install locations
  cpp/CMakeLists.txt
  cpp/python/CMakeLists.txt
Labels: bug, non-breaking

#162 Replace Python getter functions with properties in async API
  python/distributed-ucxx/distributed_ucxx/ucxx.py
  python/ucxx/_lib_async/application_context.py
  python/ucxx/_lib_async/endpoint.py
  python/ucxx/_lib_async/listener.py
  python/ucxx/_lib_async/tests/test_custom_send_recv.py
  python/ucxx/_lib_async/tests/test_disconnect.py
  python/ucxx/_lib_async/tests/test_from_worker_address_error.py
  python/ucxx/_lib_async/tests/test_probe.py
  python/ucxx/_lib_async/tests/test_reset.py
  python/ucxx/_lib_async/tests/test_send_recv_two_workers.py
  python/ucxx/_lib_async/tests/test_shutdown.py
  python/ucxx/_lib_async/tests/test_ucx_getters.py
  python/ucxx/benchmarks/backends/ucxx_async.py
  python/ucxx/core.py
Labels: breaking, improvement

#168 Replace flake8 with ruff & cython-lint
  .pre-commit-config.yaml
  python/.flake8
  python/.flake8.cython
  python/pyproject.toml
  python/ucxx/_lib/libucxx.pyx
  python/ucxx/_lib/ucxx_api.pxd
  python/ucxx/examples/python_future_task_app.pyx
Labels: improvement, non-breaking

#165 Prevent pointer conversion within `@classmethod` and improve Cython typing
  python/ucxx/_lib/libucxx.pyx
  python/ucxx/_lib/tag.pyx
  python/ucxx/core.py
Labels: improvement, non-breaking

#169 Fix pip dependencies
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  dependencies.yaml
  python/pyproject.toml
Labels: improvement, non-breaking

#172 Don't export dependency on ucx
  cpp/CMakeLists.txt
  python/CMakeLists.txt
Labels: bug, non-breaking

#176 Branch 0.37 merge branch 0.36
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .gitignore
  .pre-commit-config.yaml
  ci/build_docs.sh
  ci/checks/doxygen.sh
  ci/release/update-version.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  cpp/doxygen/Doxyfile
  cpp/include/ucxx/address.h
  cpp/include/ucxx/buffer.h
  cpp/include/ucxx/component.h
  cpp/include/ucxx/config.h
  cpp/include/ucxx/constructors.h
  cpp/include/ucxx/context.h
  cpp/include/ucxx/delayed_submission.h
  cpp/include/ucxx/endpoint.h
  cpp/include/ucxx/exception.h
  cpp/include/ucxx/future.h
  cpp/include/ucxx/header.h
  cpp/include/ucxx/inflight_requests.h
  cpp/include/ucxx/internal/request_am.h
  cpp/include/ucxx/listener.h
  cpp/include/ucxx/log.h
  cpp/include/ucxx/notifier.h
  cpp/include/ucxx/request.h
  cpp/include/ucxx/request_am.h
  cpp/include/ucxx/request_data.h
  cpp/include/ucxx/request_helper.h
  cpp/include/ucxx/request_stream.h
  cpp/include/ucxx/request_tag.h
  cpp/include/ucxx/request_tag_multi.h
  cpp/include/ucxx/typedefs.h
  cpp/include/ucxx/utils/callback_notifier.h
  cpp/include/ucxx/worker.h
  cpp/include/ucxx/worker_progress_thread.h
  cpp/python/include/ucxx/python/future.h
  cpp/python/include/ucxx/python/notifier.h
  cpp/python/include/ucxx/python/python_future.h
  cpp/python/include/ucxx/python/python_future_task.h
  cpp/python/include/ucxx/python/python_future_task_collector.h
  cpp/python/include/ucxx/python/worker.h
  cpp/src/worker.cpp
  dependencies.yaml
  python/distributed-ucxx/distributed_ucxx/tests/test_ucxx.py
  python/pyproject.toml
  python/ucxx/_lib/tests/test_server_client.py
  python/ucxx/_lib_async/continuous_ucx_progress.py
  python/ucxx/_lib_async/endpoint.py
  python/ucxx/benchmarks/asyncssh.py
Labels: improvement, non-breaking

#175 Make finding ucx conditional
  cpp/CMakeLists.txt
Labels: bug, non-breaking

#177 Use doxygen 1.9.1.
  ci/checks/doxygen.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-120_arch-x86_64.yaml
  cpp/doxygen/Doxyfile
  cpp/python/include/ucxx/python/worker.h
  dependencies.yaml
Labels: improvement, non-breaking
