Repository rapidsai/ucxx, pull requests merged in 2024-02, with the labels that each got.

#183 Run tests requiring Distributed internals separately
  ci/test_common.sh
  ci/test_python.sh
  ci/test_wheel_distributed_ucxx.sh
  python/distributed-ucxx/distributed_ucxx/tests/test_ucxx.py
  python/distributed-ucxx/distributed_ucxx/tests_internal/conftest.py
  python/distributed-ucxx/distributed_ucxx/tests_internal/test_distributed_comms.py
Labels: improvement, non-breaking

#188 Exclude tests from builds
  python/pyproject.toml
Labels: bug, non-breaking

#161 Support CUDA 12.2
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  conda/environments/all_cuda-122_arch-x86_64.yaml
  conda/recipes/ucxx/meta.yaml
  dependencies.yaml
Labels: DO NOT MERGE

#193 Pin Distributed dev mode installed in CI
  ci/test_common.sh
Labels: bug, non-breaking

#190 Add `ucxx::MemoryHandle` and `ucxx::RemoteKey` C++ classes
  cpp/CMakeLists.txt
  cpp/include/ucxx/api.h
  cpp/include/ucxx/constructors.h
  cpp/include/ucxx/context.h
  cpp/include/ucxx/memory_handle.h
  cpp/include/ucxx/remote_key.h
  cpp/include/ucxx/typedefs.h
  cpp/src/context.cpp
  cpp/src/memory_handle.cpp
  cpp/src/remote_key.cpp
  cpp/tests/CMakeLists.txt
  cpp/tests/rma.cpp
Labels: feature request, non-breaking

#191 target branch-24.04 for GitHub Actions workflows
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#185 Update ops-bot.yaml
  .github/ops-bot.yaml
Labels: improvement, non-breaking

#195 Fix `ucxx` constraints
  conda/recipes/ucxx/meta.yaml
Labels: bug, non-breaking

#198 Make (de-)allocation in `ucxx::Address` consistent
  cpp/src/address.cpp
Labels: bug, non-breaking

#199 Add support for Python 3.11, require NumPy 1.23+
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-122_arch-x86_64.yaml
  conda/recipes/ucxx/conda_build_config.yaml
  conda/recipes/ucxx/meta.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/pyproject.toml
Labels: improvement, non-breaking
