Repository rapidsai/ucxx, pull requests merged in 2024-07, with the labels that each got.

#241 remove management of UCX system libraries in build scripts
  ci/build_wheel.sh
Labels: improvement, non-breaking

#244 skip CMake 3.30.0
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-122_arch-x86_64.yaml
  dependencies.yaml
  python/pyproject.toml
Labels: improvement, non-breaking

#243 Use verify-alpha-spec hook
  .pre-commit-config.yaml
  ci/release/update-version.sh
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
Labels: improvement, non-breaking

#247 Use workflow branch 24.08 again
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#251 split up CUDA-suffixed dependencies in dependencies.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/pyproject.toml
Labels: improvement, non-breaking

#253 Merge branch-0.39 into branch-0.40
  ci/test_common.sh
  cpp/benchmarks/perftest.cpp
  cpp/include/ucxx/constructors.h
  cpp/include/ucxx/context.h
  cpp/include/ucxx/delayed_submission.h
  cpp/include/ucxx/endpoint.h
  cpp/include/ucxx/inflight_requests.h
  cpp/include/ucxx/memory_handle.h
  cpp/include/ucxx/utils/callback_notifier.h
  cpp/include/ucxx/worker.h
  cpp/include/ucxx/worker_progress_thread.h
  cpp/src/context.cpp
  cpp/src/delayed_submission.cpp
  cpp/src/endpoint.cpp
  cpp/src/inflight_requests.cpp
  cpp/src/listener.cpp
  cpp/src/memory_handle.cpp
  cpp/src/utils/callback_notifier.cpp
  cpp/src/worker.cpp
  cpp/src/worker_progress_thread.cpp
  cpp/tests/request.cpp
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/pyproject.toml
  python/ucxx/_lib_async/tests/test_endpoint.py
Labels: improvement, non-breaking

#255 Mark C++ constructors and getters `[[nodiscard]]`
  cpp/include/ucxx/address.h
  cpp/include/ucxx/buffer.h
  cpp/include/ucxx/component.h
  cpp/include/ucxx/config.h
  cpp/include/ucxx/context.h
  cpp/include/ucxx/delayed_submission.h
  cpp/include/ucxx/endpoint.h
  cpp/include/ucxx/future.h
  cpp/include/ucxx/header.h
  cpp/include/ucxx/inflight_requests.h
  cpp/include/ucxx/listener.h
  cpp/include/ucxx/memory_handle.h
  cpp/include/ucxx/remote_key.h
  cpp/include/ucxx/request.h
  cpp/include/ucxx/request_am.h
  cpp/include/ucxx/request_endpoint_close.h
  cpp/include/ucxx/request_flush.h
  cpp/include/ucxx/request_mem.h
  cpp/include/ucxx/request_stream.h
  cpp/include/ucxx/request_tag.h
  cpp/include/ucxx/request_tag_multi.h
  cpp/include/ucxx/utils/file_descriptor.h
  cpp/include/ucxx/utils/python.h
  cpp/include/ucxx/utils/sockaddr.h
  cpp/include/ucxx/worker.h
  cpp/include/ucxx/worker_progress_thread.h
  cpp/python/include/ucxx/python/exception.h
  cpp/python/include/ucxx/python/future.h
  cpp/python/include/ucxx/python/notifier.h
  cpp/python/include/ucxx/python/python_future.h
  cpp/python/include/ucxx/python/python_future_task.h
  cpp/python/include/ucxx/python/python_future_task_collector.h
  cpp/python/include/ucxx/python/worker.h
  cpp/python/src/python_future.cpp
  cpp/src/config.cpp
  cpp/src/delayed_submission.cpp
  cpp/src/listener.cpp
  cpp/src/worker.cpp
  cpp/tests/buffer.cpp
Labels: feature request, non-breaking

#256 Drop `numpy` from `requirements/host`
  conda/recipes/ucxx/meta.yaml
Labels: bug, non-breaking
