Repository rapidsai/ucxx, pull requests merged in 2025-05, with the labels that each got.

#401 fix(rattler): produce multiple python outputs
  build.sh
  conda/recipes/ucxx/build_and_install_ucxx_tests.sh
  conda/recipes/ucxx/install_libucxx.sh
  conda/recipes/ucxx/meta.yaml
  conda/recipes/ucxx/recipe.yaml
Labels: improvement, non-breaking

#403 fix(rattler): restore ucxx-tests package
  conda/recipes/ucxx/recipe.yaml
Labels: improvement, non-breaking

#406 Add support for Python 3.13
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  conda/environments/all_cuda-118_arch-aarch64.yaml
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/recipes/ucxx/conda_build_config.yaml
  conda/recipes/ucxx/recipe.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#410 Add Python to distributed-ucxx Conda build string
  conda/recipes/ucxx/recipe.yaml
Labels: bug, non-breaking

#411 Exclude librmm.so from auditwheel
  ci/build_wheel_libucxx.sh
  ci/build_wheel_ucxx.sh
Labels: feature request, non-breaking

#409 chore: set remaining workflows to python3.13
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#412 Build and test with CUDA 12.9.0
  .devcontainer/cuda12.9-conda/devcontainer.json
  .devcontainer/cuda12.9-pip/devcontainer.json
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  README.md
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#413 Quote head_rev in conda recipes
  conda/recipes/ucxx/recipe.yaml
Labels: improvement, non-breaking

#414 Update to clang 20
  .pre-commit-config.yaml
  cpp/include/ucxx/log.h
  cpp/src/request_tag_multi.cpp
Labels: improvement, non-breaking

#408 Forward-merge branch-0.44 into branch-0.45
  .devcontainer/cuda12.9-conda/devcontainer.json
  .devcontainer/cuda12.9-pip/devcontainer.json
  .github/workflows/pr.yaml
  README.md
  ci/build_wheel_libucxx.sh
  ci/build_wheel_ucxx.sh
  conda/environments/all_cuda-118_arch-aarch64.yaml
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/recipes/ucxx/conda_build_config.yaml
  conda/recipes/ucxx/recipe.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#416 Finish CUDA 12.9 migration and use branch-25.06 workflows
  .devcontainer/cuda12.8-conda/devcontainer.json
  .devcontainer/cuda12.8-pip/devcontainer.json
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  README.md
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#418 Fix persist usage in tests
  python/distributed-ucxx/distributed_ucxx/tests/test_ucxx.py
Labels: bug, non-breaking

#419 Branch 0.45 merge branch 0.44
  .devcontainer/cuda12.8-conda/devcontainer.json
  .devcontainer/cuda12.8-pip/devcontainer.json
  README.md
  conda/environments/all_cuda-128_arch-aarch64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
  python/distributed-ucxx/distributed_ucxx/tests/test_ucxx.py
Labels: improvement, non-breaking

#420 Add back Python 3.13 builds
  conda/recipes/ucxx/conda_build_config.yaml
Labels: improvement, non-breaking

#421 use 'rapids-init-pip' in wheel CI, other CI changes
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/build_wheel.sh
  ci/build_wheel_distributed_ucxx.sh
  ci/build_wheel_libucxx.sh
  ci/build_wheel_ucxx.sh
  ci/test_wheel_distributed_ucxx.sh
  ci/test_wheel_ucxx.sh
Labels: improvement, non-breaking

#427 Avoid linking to libpython
  cpp/python/CMakeLists.txt
  python/ucxx/ucxx/_lib/CMakeLists.txt
  python/ucxx/ucxx/examples/CMakeLists.txt
Labels: bug, non-breaking

#429 feat(cmake): add cmake prefix to `ucxx` `pyproject.toml`
  cpp/python/CMakeLists.txt
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking
