Repository rapidsai/ucxx, pull requests merged in 2025-03, with the labels that each got.

#380 Update RAPIDS version in `conda_build_config.yaml`
  ci/release/update-version.sh
Labels: improvement, non-breaking

#381 Add shellcheck to pre-commit and fix warnings
  .pre-commit-config.yaml
  build.sh
  build_and_run.sh
  ci/build_docs.sh
  ci/build_wheel_distributed_ucxx.sh
  ci/build_wheel_libucxx.sh
  ci/build_wheel_ucxx.sh
  ci/checks/doxygen.sh
  ci/release/update-version.sh
  ci/test_common.sh
  ci/test_cpp.sh
  ci/test_wheel_distributed_ucxx.sh
  ci/test_wheel_ucxx.sh
  ci/validate_wheel.sh
  conda/recipes/ucxx/build.sh
Labels: improvement, non-breaking

#382 Make `tagProbe` non-blocking
  cpp/include/ucxx/worker.h
  cpp/src/worker.cpp
  python/ucxx/ucxx/_lib_async/tests/test_probe.py
Labels: breaking, bug

#383 Fix update-version.sh
  ci/release/update-version.sh
Labels: bug, non-breaking

#384 Enable protov2 by default on UCX >= 1.18.0
  python/ucxx/ucxx/__init__.py
Labels: breaking, feature request

#385 Set a timeout for event loop in async tests
  python/ucxx/ucxx/_lib_async/tests/conftest.py
  python/ucxx/ucxx/_lib_async/tests/test_disconnect.py
  python/ucxx/ucxx/_lib_async/tests/test_from_worker_address.py
  python/ucxx/ucxx/_lib_async/tests/test_from_worker_address_error.py
  python/ucxx/ucxx/_lib_async/tests/test_send_recv_two_workers.py
  python/ucxx/ucxx/_lib_async/utils_test.py
Labels: improvement, non-breaking

#390 Remove `UCXAddress.string` in favor of `__bytes__`
  python/ucxx/ucxx/_lib/libucxx.pyx
  python/ucxx/ucxx/_lib/tests/test_address_object.py
Labels: breaking, improvement
