Repository rapidsai/ucxx, pull requests merged in 2025-02, with the labels that each got.

#363 disallow fallback to Make, add devcontainers CI
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/cuda11.8-conda/devcontainer.json
  .devcontainer/cuda11.8-pip/devcontainer.json
  .devcontainer/cuda12.8-conda/devcontainer.json
  .devcontainer/cuda12.8-pip/devcontainer.json
  .github/workflows/pr.yaml
  ci/release/update-version.sh
  python/libucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#366 Use `rapids-pip-retry` in CI jobs that might need retries
  .pre-commit-config.yaml
  ci/build_wheel.sh
  ci/build_wheel_libucxx.sh
  ci/test_wheel_distributed_ucxx.sh
  ci/test_wheel_ucxx.sh
Labels: improvement, non-breaking

#367 Add build_type input field for `test.yaml`
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#368 Use shared-workflows branch-25.04
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#369 Use rapids-generate-version for package versions
  ci/build_cpp.sh
  conda/recipes/ucxx/meta.yaml
Labels: improvement, non-breaking

#370 Enable label checker ops-bot plugin
  .github/ops-bot.yaml
Labels: improvement, non-breaking

#364 Use new rapids-logger library
  ci/build_wheel_libucxx.sh
  ci/build_wheel_ucxx.sh
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  cpp/CMakeLists.txt
  cpp/python/CMakeLists.txt
  dependencies.yaml
  python/libucxx/libucxx/load.py
  python/libucxx/pyproject.toml
Labels: improvement, non-breaking

#321 add telemetry
  .github/workflows/pr.yaml
Labels: improvement, non-breaking, Needs build-infra

#373 Create Conda CI test env in one step
  ci/release/update-version.sh
  ci/test_cpp.sh
  ci/test_python.sh
  ci/test_python_distributed.sh
  dependencies.yaml
Labels: improvement, non-breaking

#375 Consolidate more Conda solves in CI
  ci/build_docs.sh
  dependencies.yaml
Labels: improvement, non-breaking

#372 Expose class structure in `libucxx.pxd`
  python/ucxx/ucxx/_lib/libucxx.pxd
  python/ucxx/ucxx/_lib/libucxx.pyx
Labels: feature request, non-breaking

#378 Use conda-build instead of conda-mambabuild
  ci/build_cpp.sh
Labels: improvement, non-breaking

#379 Register gpu marker with pytest
  python/distributed-ucxx/pyproject.toml
Labels: improvement, non-breaking
