Repository rapidsai/ucxx, pull requests merged in 2025-09, with the labels that each got.

#495 Remove setting of RMM_LOG_ACTIVE_LEVEL
  cpp/CMakeLists.txt
Labels: improvement, non-breaking

#499 Prevent installation of pytest-rerunfailures 16.0.0
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/environments/all_cuda-130_arch-aarch64.yaml
  conda/environments/all_cuda-130_arch-x86_64.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#498 use 'nvidia-ml-py' package for 'pynvml' module
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/environments/all_cuda-130_arch-aarch64.yaml
  conda/environments/all_cuda-130_arch-x86_64.yaml
  conda/recipes/ucxx/recipe.yaml
  dependencies.yaml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#497 Add configuration schema for distributed-ucxx
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  conda/environments/all_cuda-130_arch-aarch64.yaml
  conda/environments/all_cuda-130_arch-x86_64.yaml
  conda/recipes/ucxx/recipe.yaml
  dependencies.yaml
  python/distributed-ucxx/README.md
  python/distributed-ucxx/distributed_ucxx/config.py
  python/distributed-ucxx/distributed_ucxx/distributed-ucxx-schema.yaml
  python/distributed-ucxx/distributed_ucxx/distributed-ucxx.yaml
  python/distributed-ucxx/distributed_ucxx/tests/test_ucxx_config.py
  python/distributed-ucxx/distributed_ucxx/ucxx.py
  python/distributed-ucxx/pyproject.toml
Labels: feature request, non-breaking

#506 Use branch-25.10 again
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#507 Make ucx target global
  cpp/CMakeLists.txt
Labels: bug, non-breaking

#503 Fix issue 502
  python/ucxx/ucxx/benchmarks/backends/asyncio.py
  python/ucxx/ucxx/benchmarks/backends/socket.py
  python/ucxx/ucxx/benchmarks/backends/tornado.py
  python/ucxx/ucxx/benchmarks/backends/ucxx_async.py
  python/ucxx/ucxx/benchmarks/backends/ucxx_core.py
  python/ucxx/ucxx/benchmarks/send_recv.py
Labels: feature request, non-breaking, ucxx

#513 Configure repo for automatic release notes generation
  .github/release.yml
Labels: improvement, non-breaking

#516 Make send/put buffer pointers const
  cpp/include/ucxx/endpoint.h
  cpp/include/ucxx/request_data.h
  cpp/src/endpoint.cpp
  cpp/src/request_data.cpp
  cpp/tests/request.cpp
  cpp/tests/worker.cpp
  python/ucxx/ucxx/_lib/libucxx.pyx
  python/ucxx/ucxx/_lib/ucxx_api.pxd
Labels: breaking, improvement, libucxx

#526 Add support for RMM in C++ example
  build.sh
  build_and_run.sh
  ci/run_cpp.sh
  cpp/examples/basic.cpp
  cpp/include/ucxx/buffer.h
  cpp/src/buffer.cpp
Labels: improvement, non-breaking, libucxx

#521 Add precision logic to floatToString
  cpp/benchmarks/perftest.cpp
Labels: bug, non-breaking, libucxx
