Repository rapidsai/ucxx, pull requests merged in 2025-07, with the labels that each got.

#445 Fix `ucxx::Endpoint::close()` callback function use
  cpp/src/endpoint.cpp
  cpp/tests/listener.cpp
Labels: bug, non-breaking

#453 Override default progress mode for distributed-ucxx
  python/distributed-ucxx/distributed_ucxx/ucxx.py
Labels: feature request, non-breaking

#456 Run all C++ tests with protov2
  ci/run_cpp.sh
Labels: improvement, non-breaking

#461 Remove CUDA 11 from README
  README.md
Labels: improvement, non-breaking

#462 Update to numba-cuda>=0.16
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  dependencies.yaml
  python/distributed-ucxx/distributed_ucxx/ucxx.py
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: feature request, non-breaking

#463 Fix numba-cuda wheel package dependency
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: bug, non-breaking

#464 Fix CI run script
  ci/run_python_distributed.sh
Labels: bug, non-breaking

#466 Use numba-cuda>=0.15.2,<0.16
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#471 Restructure and improve `ucxx_perftest`
  README.md
  ci/run_cpp.sh
  ci/run_cpp_benchmarks.sh
  ci/test_common.sh
  ci/test_cpp.sh
  cpp/benchmarks/include/buffer_interface.hpp
  cpp/benchmarks/perftest.cpp
Labels: breaking, improvement

#474 Fix build warnings in C++ tests
  cpp/tests/buffer.cpp
  cpp/tests/request.cpp
  cpp/tests/rma.cpp
Labels: bug, non-breaking

#438 Remove pytest pin
  ci/run_python.sh
  conda/environments/all_cuda-129_arch-aarch64.yaml
  conda/environments/all_cuda-129_arch-x86_64.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
  python/ucxx/ucxx/_lib_async/tests/conftest.py
  python/ucxx/ucxx/_lib_async/tests/test_custom_send_recv.py
Labels: improvement, non-breaking
