Repository rapidsai/ucxx, pull requests merged in 2025-01, with the labels that each got.

#348 Improve `tagProbe` and AM receiver callback
  cpp/include/ucxx/typedefs.h
  cpp/include/ucxx/worker.h
  cpp/src/internal/request_am.cpp
  cpp/src/worker.cpp
  cpp/tests/request.cpp
  cpp/tests/worker.cpp
  python/ucxx/ucxx/_lib/libucxx.pyx
  python/ucxx/ucxx/_lib/ucxx_api.pxd
Labels: breaking, feature request

#349 Retain copy of header for AM send requests
  cpp/include/ucxx/request_am.h
  cpp/src/request_am.cpp
Labels: bug, non-breaking

#347 Use GCC 13 in CUDA 12 conda builds.
  conda/recipes/ucxx/conda_build_config.yaml
  conda/recipes/ucxx/meta.yaml
Labels: improvement, non-breaking

#352 Increase UCX upper pin to 1.19
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/recipes/ucxx/meta.yaml
  dependencies.yaml
  python/libucxx/pyproject.toml
Labels: improvement, non-breaking

#351 Add upper bound to prevent usage of numba 0.61.0
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/recipes/ucxx/meta.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#354 Fix minimum `numba` version pinning typo
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-125_arch-x86_64.yaml
  conda/recipes/ucxx/meta.yaml
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: bug, non-breaking

#355 Remove `std::mutex()` from list-initialization
  cpp/include/ucxx/endpoint.h
Labels: bug, non-breaking

#357 Build and test with CUDA 12.8.0
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  README.md
  conda/environments/all_cuda-128_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#360 Revert CUDA 12.8 shared workflow branch changes
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#361 Forward-merge branch-0.42 into branch-0.43
  README.md
  conda/environments/all_cuda-118_arch-x86_64.yaml
  conda/environments/all_cuda-128_arch-x86_64.yaml
  conda/recipes/ucxx/meta.yaml
  cpp/include/ucxx/endpoint.h
  dependencies.yaml
  python/distributed-ucxx/pyproject.toml
  python/ucxx/pyproject.toml
Labels: improvement, non-breaking

#358 Migrate to NVKS for amd64 CI runners
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking
